services:
  app:
    build:
      context: ./4d-manifold-baryon-demo/app
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - NODE_ENV=production
    depends_on:
      - db
      - dsim

  db:
    image: postgres:16
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data

  dsim:
    build:
      context: ./DSIM_Simulation
      dockerfile: Dockerfile
    container_name: dsim-svc
    command: python -c "print('DSIM service up')"
    volumes:
      - ./DSIM_Simulation:/app

volumes:
  db-data: 