name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: |
          if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
          elif [ -f package-lock.json ]; then npm ci; \
          elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm i; \
          elif [ -f .yarnrc.yml ]; then yarn install; \
          else npm install; \
          fi
        working-directory: ./skb-baryon-demo/app
      - name: Lint
        run: npm run lint
        working-directory: ./skb-baryon-demo/app
      - name: Build
        run: npm run build
        working-directory: ./skb-baryon-demo/app
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Docker image
        run: docker build -t skb-baryon-demo .
        working-directory: ./skb-baryon-demo/app
      # Add test steps if tests are available 